spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: douyin-basic
  resources:
    static-locations: classpath:static/
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
    redis:
      # 缓存空值，解决缓存穿透问题
      cache-null-values: true
      use-key-prefix: true
      # 设置缓存过期时间
      time-to-live: 3600000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10010


## 视频配置
video-config:
  ##Server地址前缀
  server-path: http://192.168.1.106:10010/ # your server-path
  ##视频保存路径
  video-save-path: videos #your target folder name
  ##视频封面保存路径
  video-cover-save-path: covers #your target folder name
  ##配置封面截取第几帧
  frame-num: 1
  ##feed流至多返回多少条视频
  feed-video-max-num: 15
