spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: douyin-basic
  resources:
    static-locations: classpath:static/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10010


## 视频配置
video-config:
  ##Server地址前缀
<<<<<<< HEAD
  server-path: http://169.254.203.62:10010/ # your server-path
=======
  server-path: http://192.168.1.106:10001/ # your server-path
>>>>>>> 523eef1740a8a0207c12142d39faae74296f11ad
  ##视频保存路径
  video-save-path: videos #your target folder name
  ##视频封面保存路径
  video-cover-save-path: covers #your target folder name
  ##配置封面截取第几帧
  frame-num: 1
  ##feed流至多返回多少条视频
  feed-video-max-num: 15
